"""Pydantic schemas."""
from app.schemas.base import BaseSchema, IDMixin, TimestampMixin
from app.schemas.curriculum import (
    OutcomeCreate,
    OutcomeListResponse,
    OutcomeQueryParams,
    OutcomeResponse,
    OutcomeSummary,
    OutcomeUpdate,
    StrandInfo,
    StrandListResponse,
)
from app.schemas.framework import (
    FrameworkCreate,
    FrameworkListResponse,
    FrameworkResponse,
    FrameworkSummary,
    FrameworkUpdate,
)
from app.schemas.health import HealthResponse
from app.schemas.senior_course import (
    SeniorCourseCreate,
    SeniorCourseListResponse,
    SeniorCourseResponse,
    SeniorCourseSummary,
    SeniorCourseUpdate,
)
from app.schemas.student import (
    GamificationData,
    StudentCreate,
    StudentListResponse,
    StudentResponse,
    StudentSummary,
    StudentUpdate,
)
from app.schemas.subject import (
    SubjectConfig,
    SubjectCreate,
    SubjectListResponse,
    SubjectResponse,
    SubjectSummary,
    SubjectUpdate,
)
from app.schemas.student_subject import (
    BulkEnrolmentRequest,
    BulkEnrolmentResponse,
    EnrolmentRequest,
    StudentSubjectCreate,
    StudentSubjectListResponse,
    StudentSubjectProgress,
    StudentSubjectProgressUpdate,
    StudentSubjectResponse,
    StudentSubjectUpdate,
    StudentSubjectWithDetails,
)
from app.schemas.user import UserCreate, UserResponse, UserSummary, UserUpdate
from app.schemas.session import (
    SessionCreate,
    SessionData,
    SessionEndRequest,
    SessionListResponse,
    SessionResponse,
    SessionStatsUpdate,
    SessionUpdate,
)
from app.schemas.ai_interaction import (
    AIInteractionListResponse,
    AIInteractionResponse,
    ChatHistoryMessage,
    ChatHistoryResponse,
    ChatRequest,
    ChatResponse,
    CurriculumContext,
    FlashcardItem,
    FlashcardRequest,
    FlashcardResponse,
    InteractionFlagRequest,
    SummariseRequest,
    SummariseResponse,
    TokenUsageResponse,
)
from app.schemas.note import (
    CurriculumAlignmentResponse,
    CurriculumSuggestion,
    NoteCreate,
    NoteListResponse,
    NoteResponse,
    NoteSearchResponse,
    NoteSearchResult,
    NoteUpdate,
    OCRStatusResponse,
    OutcomeUpdateRequest,
    UploadUrlRequest,
    UploadUrlResponse,
)
from app.schemas.goal import (
    GoalAchievement,
    GoalCreate,
    GoalListResponse,
    GoalProgress,
    GoalResponse,
    GoalSummary,
    GoalUpdate,
)
from app.schemas.notification import (
    DeliveryMethodEnum,
    EmailFrequencyEnum,
    NotificationCreate,
    NotificationListResponse,
    NotificationMarkReadRequest,
    NotificationMarkReadResponse,
    NotificationPreferencesResponse,
    NotificationPreferencesUpdate,
    NotificationPriorityEnum,
    NotificationResponse,
    NotificationSummary,
    NotificationTypeEnum,
    WeekDayEnum,
)
from app.schemas.weekly_insight import (
    HSCProjection,
    InsightGenerationRequest,
    InsightItem,
    PathwayReadiness,
    RecommendationItem,
    WeeklyInsightCreate,
    WeeklyInsightListResponse,
    WeeklyInsightResponse,
    WeeklyInsightsData,
)
from app.schemas.parent_dashboard import (
    DashboardOverviewResponse,
    DashboardStudentSummary,
    FoundationStrength,
    SendWeeklySummaryRequest,
    SendWeeklySummaryResponse,
    StrandProgress,
    StudentProgressResponse,
    SubjectProgress,
    SubjectProgressDetailResponse,
    WeeklyStats,
    WeeklySummaryResponse,
)

__all__ = [
    # Base
    "BaseSchema",
    "IDMixin",
    "TimestampMixin",
    # Health
    "HealthResponse",
    # Framework
    "FrameworkCreate",
    "FrameworkUpdate",
    "FrameworkResponse",
    "FrameworkListResponse",
    "FrameworkSummary",
    # Subject
    "SubjectConfig",
    "SubjectCreate",
    "SubjectUpdate",
    "SubjectResponse",
    "SubjectSummary",
    "SubjectListResponse",
    # Curriculum Outcome
    "OutcomeCreate",
    "OutcomeUpdate",
    "OutcomeResponse",
    "OutcomeSummary",
    "OutcomeListResponse",
    "OutcomeQueryParams",
    "StrandInfo",
    "StrandListResponse",
    # Senior Course
    "SeniorCourseCreate",
    "SeniorCourseUpdate",
    "SeniorCourseResponse",
    "SeniorCourseSummary",
    "SeniorCourseListResponse",
    # User
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserSummary",
    # Student
    "StudentCreate",
    "StudentUpdate",
    "StudentResponse",
    "StudentSummary",
    "StudentListResponse",
    "GamificationData",
    # Student Subject / Enrolment
    "StudentSubjectCreate",
    "StudentSubjectUpdate",
    "StudentSubjectResponse",
    "StudentSubjectProgress",
    "StudentSubjectProgressUpdate",
    "StudentSubjectWithDetails",
    "StudentSubjectListResponse",
    "EnrolmentRequest",
    "BulkEnrolmentRequest",
    "BulkEnrolmentResponse",
    # Session
    "SessionCreate",
    "SessionUpdate",
    "SessionResponse",
    "SessionListResponse",
    "SessionData",
    "SessionEndRequest",
    "SessionStatsUpdate",
    # AI Interaction
    "AIInteractionResponse",
    "AIInteractionListResponse",
    "ChatRequest",
    "ChatResponse",
    "ChatHistoryMessage",
    "ChatHistoryResponse",
    "FlashcardItem",
    "FlashcardRequest",
    "FlashcardResponse",
    "SummariseRequest",
    "SummariseResponse",
    "CurriculumContext",
    "TokenUsageResponse",
    "InteractionFlagRequest",
    # Note
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "NoteListResponse",
    "NoteSearchResult",
    "NoteSearchResponse",
    "UploadUrlRequest",
    "UploadUrlResponse",
    "OCRStatusResponse",
    "CurriculumSuggestion",
    "CurriculumAlignmentResponse",
    "OutcomeUpdateRequest",
    # Goal
    "GoalCreate",
    "GoalUpdate",
    "GoalResponse",
    "GoalSummary",
    "GoalListResponse",
    "GoalProgress",
    "GoalAchievement",
    # Notification
    "NotificationCreate",
    "NotificationResponse",
    "NotificationSummary",
    "NotificationListResponse",
    "NotificationMarkReadRequest",
    "NotificationMarkReadResponse",
    "NotificationPreferencesUpdate",
    "NotificationPreferencesResponse",
    "NotificationTypeEnum",
    "NotificationPriorityEnum",
    "DeliveryMethodEnum",
    "EmailFrequencyEnum",
    "WeekDayEnum",
    # Weekly Insight
    "InsightItem",
    "RecommendationItem",
    "PathwayReadiness",
    "HSCProjection",
    "WeeklyInsightsData",
    "WeeklyInsightResponse",
    "WeeklyInsightCreate",
    "WeeklyInsightListResponse",
    "InsightGenerationRequest",
    # Parent Dashboard
    "DashboardStudentSummary",
    "WeeklyStats",
    "StrandProgress",
    "SubjectProgress",
    "FoundationStrength",
    "DashboardOverviewResponse",
    "StudentProgressResponse",
    "SubjectProgressDetailResponse",
    "WeeklySummaryResponse",
    "SendWeeklySummaryRequest",
    "SendWeeklySummaryResponse",
]
