/**
 * Custom service worker for StudyHub PWA.
 * Handles push notifications and offline caching.
 */

/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

// Type for push subscription change event (not yet in standard TypeScript lib)
interface PushSubscriptionChangeEvent extends ExtendableEvent {
  readonly oldSubscription: PushSubscription | null;
  readonly newSubscription: PushSubscription | null;
}

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Cache API responses with network-first strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/subjects'),
  new StaleWhileRevalidate({
    cacheName: 'curriculum-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/curriculum'),
  new StaleWhileRevalidate({
    cacheName: 'curriculum-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/frameworks'),
  new StaleWhileRevalidate({
    cacheName: 'curriculum-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache other API responses with network-first
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Cache images with cache-first
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// Push notification handling
self.addEventListener('push', (event) => {
  if (!event.data) {
    console.log('Push event but no data');
    return;
  }

  try {
    const data = event.data.json();

    // NotificationOptions extended with service worker specific properties
    const options = {
      body: data.body || 'You have a new notification',
      icon: data.icon || '/pwa-192x192.svg',
      badge: data.badge || '/pwa-192x192.svg',
      tag: data.tag || 'studyhub-notification',
      data: data.data || {},
      actions: data.actions || [],
      vibrate: [100, 50, 100],
      requireInteraction: data.requireInteraction || false,
    } as NotificationOptions;

    event.waitUntil(
      self.registration.showNotification(data.title || 'StudyHub', options)
    );
  } catch (error) {
    console.error('Error showing push notification:', error);
  }
});

// Notification click handling
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const data = event.notification.data || {};
  let url = '/';

  // Handle different notification types
  if (data.type === 'study_reminder') {
    url = '/revision';
  } else if (data.type === 'achievement') {
    url = '/achievements';
  } else if (data.type === 'streak') {
    url = '/';
  } else if (data.url) {
    url = data.url;
  }

  // Handle action clicks
  if (event.action) {
    switch (event.action) {
      case 'study_now':
        url = '/revision';
        break;
      case 'view':
        url = data.url || '/';
        break;
      case 'dismiss':
        return;
    }
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Focus existing window if available
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      // Open new window if no existing window
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});

// Handle notification close
self.addEventListener('notificationclose', (event) => {
  console.log('Notification closed:', event.notification.tag);
});

// Handle push subscription change
self.addEventListener('pushsubscriptionchange', (event) => {
  console.log('Push subscription changed');
  const pushEvent = event as PushSubscriptionChangeEvent;

  event.waitUntil(
    // Re-subscribe and update the server
    self.registration.pushManager
      .subscribe({
        userVisibleOnly: true,
        applicationServerKey: pushEvent.oldSubscription?.options?.applicationServerKey,
      })
      .then((subscription) => {
        // Send new subscription to server
        return fetch('/api/v1/push/subscribe', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            endpoint: subscription.endpoint,
            keys: {
              p256dh: btoa(
                String.fromCharCode(...new Uint8Array(subscription.getKey('p256dh')!))
              ),
              auth: btoa(
                String.fromCharCode(...new Uint8Array(subscription.getKey('auth')!))
              ),
            },
          }),
        });
      })
      .catch((error) => {
        console.error('Failed to resubscribe:', error);
      })
  );
});

// Skip waiting and claim clients immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
